import time
print("Welcome to the Band Name Generator.")
city = input("Which city did you grow up in?\n")
fruit = input("if you could eat only a single fruit in your life what would it be ?\n")

print(f"the perfect name for someone who grew up in {city} and loves {fruit} could be")
time.sleep(0.5)
print(".", end=" ")
time.sleep(0.5)
print(".", end=" ")
time.sleep(0.5)
print(".", end=" ")
time.sleep(0.5)
print(".", end=" ")
time.sleep(0.5)
print(".", end=" ")
time.sleep(0.5)
print(".", end=" ")
time.sleep(0.5)
print(".", end=" ")
time.sleep(0.5)
print(".")
print(f"Your band name could be {city}'s {fruit}")
